api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
